name: artpia
description: Handmade Product Shop

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  image: ^2.0.7
  provider: ^4.0.4
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_auth: ^0.15.4
  path_provider: ^0.5.0+1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.2+1
  firebase_storage: ^3.1.1
  shared_preferences: ^0.5.6+1
  flutter_staggered_grid_view: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true