name: artpia
description: Handmade Product Shop

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  provider: ^4.3.3
  images_picker: ^1.2.1
  firebase_core: ^0.7.0
  path_provider: ^1.6.27
  firebase_auth: ^0.20.0+1
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  shared_preferences: ^0.5.12
  permission_handler: ^5.1.0+2
  flutter_card_swipper: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true