// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-1PFYbGydo0zdOD66cm-8uEvHg9lrupg',
    appId: '1:664940911756:web:9a31108fcd6e974660afa9',
    messagingSenderId: '664940911756',
    projectId: 'shallcook-8ec0e',
    authDomain: 'shallcook-8ec0e.firebaseapp.com',
    storageBucket: 'shallcook-8ec0e.appspot.com',
    measurementId: 'G-V0EF0RQXJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLOVgreLyRjjXSg2Fg2bF_rf2XEAuZxjk',
    appId: '1:664940911756:android:6e656c1bd7073bee60afa9',
    messagingSenderId: '664940911756',
    projectId: 'shallcook-8ec0e',
    storageBucket: 'shallcook-8ec0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFy2o2HOsXAg_QRCkPzZf1rMliPnJXJg',
    appId: '1:664940911756:ios:988e927fa8444cc960afa9',
    messagingSenderId: '664940911756',
    projectId: 'shallcook-8ec0e',
    storageBucket: 'shallcook-8ec0e.appspot.com',
    iosClientId: '664940911756-kbockb98e779vnoared78mdq3060l6sl.apps.googleusercontent.com',
    iosBundleId: 'com.mzone.mzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFy2o2HOsXAg_QRCkPzZf1rMliPnJXJg',
    appId: '1:664940911756:ios:988e927fa8444cc960afa9',
    messagingSenderId: '664940911756',
    projectId: 'shallcook-8ec0e',
    storageBucket: 'shallcook-8ec0e.appspot.com',
    iosClientId: '664940911756-kbockb98e779vnoared78mdq3060l6sl.apps.googleusercontent.com',
    iosBundleId: 'com.mzone.mzone',
  );
}
